name: 'RunActionsSecurityAnalzyer'
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**'
jobs:
  RunAsa:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3
    - name: "Run asa scanner"
      uses: "bin3xish477/asa@c9b2aaf2f038e58117f17b90a0f15f0ab4865fa4"
      with:
        dir: "./actions/"
        verbose: false
        #no-summary: true
        #ignore-checks: ''
        #ignore-warnings: true
      continue-on-error: true # adding this since this workflow is always expected to fail
